#Sun Apr 14 15:38:21 BST 2024
micronaut:
  application.name: chat-app-server
  security.enabled: false
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
